### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by imagelesskink** [MongoTheElder/TotallyNotRedstone#1]
When this mod is enables, minecraft crashes when trying to load particles for other mods.
[crash-2020-10-24_19.54.51-client.txt](https://github.com/MongoTheElder/TotallyNotRedstone/files/5433992/crash-2020-10-24_19.54.51-client.txt)

**Comment by MongoTheElder** [comment]
Not really sure where the issue is, I don't use any particle effects nor change any default file paths. I'll try to duplicate this to see if I can localize where this is breaking other mods

**Comment by MongoTheElder** [comment]
I duplicated the issue. Still don't know where the issue is. Mekanism and TNR work together by themselves so its not a 1:1 problem. When I remove some of the mods, the problem moved to IE. Still investigating...

**Comment by MongoTheElder** [comment]
So, Patchouli and Mekanism alone can cause the issue. All other mods (with the exception of Botania and Botania Additions that require Patchouli) work with TNR installed

**Comment by MongoTheElder** [comment]
Found it. I was working on adding a Patchouli book for the mod and the incomplete book definitions got into the beta build. I removed the incomplete definitions and everything looks good, Version 1.16.3-0.2.1 is in Curse review and should be released shortly
